name-template: "Example title - v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
exclude-labels:
  - "skip-changelog"
categories:
  - title: "New Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Translation"
    labels:
      - "translation"
  - title: "Dependencies"
    labels:
      - "dependencies"
      - "dependency"
  - title: "Maintenance"
    label: "maintenance"
  - title: "Code quality and optimizations"
    label: "code quality"
  - title: "Development tools"
    label: "development tools"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/aturri/ha-zcsazzurro/v$RESOLVED_VERSION/total.svg)](https://github.com/aturri/ha-zcsazzurro/releases/v$RESOLVED_VERSION)

  ### Checklist for release
  - Download translations PR from Lokalize
  - Run make lint
  - Run make bump
  - Review the draft below
  - Remove this checklist

  ## Notable Changes

  $CHANGES

autolabeler:
  - label: "maintenance"
    files:
      - "*.md"
      - ".github/*"
      - ".ruff.toml"
      - ".pre-commit-config.yaml"
  - label: "bugfix"
    title:
      - "/fix/i"
  - label: "code quality"
    title:
      - "lint"
  - label: "translation"
    title:
      - "Translation:"
    files:
      - "*/translations/*.json"
  - label: "development tools"
    files:
      - ".devcontainer/*"
      - ".devcontainer.json"
