name: Report an issue
description: Report an issue with ZCS Azzurro for Home Assistant.
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!

        If you have a feature or enhancement request, please use the applicable form
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version_zcsazzurro
    validations:
      required: true
    attributes:
      label: Version of zcsazzurro integration having the issue?
      placeholder: zcsazzurro-
      description: >
        Can be found in the Configuration panel -> Info.
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Version of Home Assistant Core having the issue?
      placeholder: core-
      description: >
        Can be found in the Configuration panel -> Info.
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        setting the cursor in the field below and dragging and dropping files into the box.
