default_config:

zcsazzurro:
  auth_key: !secret zcs.authkey
  client_code: !secret zcs.clientcode

logger:
  default: info
  logs:
    custom_components.zcsazzurro: debug
    pyzcsazzurro: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy: